---
- name: Restart 'sshd' Service
  service:
    name: sshd
    state: restarted
  listen: "Restart SSH Service"

- name: Restart 'chronyd' Service
  service:
    name: chronyd
    state: started
  listen: "Start Time Service"

- name: Restart 'networking' Service
  service:
    name: networking
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  listen: "Start Network Service"

- name: Restart 'network' Service
  service:
    name: network
    state: restarted
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  listen: "Restart Network Service"