---
- name: Install 'ifupdown' on 'Ubuntu' / 'Debian'
  package:
    name: ifupdown
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags: [network]

- name: Configure '/etc/network/interfaces.d/eth0.conf' File
  template:
    src: eth0.conf.j2
    dest: /etc/network/interfaces.d/eth0.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  notify: "Restart Network Service"
  tags: [network]

- name: Uninstall 'netplan.io' from 'Ubuntu' / 'Debian'
  package:
    name: netplan.io
    state: absent
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags: [network]

- name: Configure '/etc/sysconfig/network-scripts/ifcfg-eth0' File
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  notify: "Restart Network Service"
  tags: [network]