---
- name: Create `/root/cron.d` Directory
  file:
    path: /root/cron.d
    owner: root
    group: root
    state: directory
    mode: '0700'
  tags: [cron]

- name: Create `/root/cron.d/system` Directory
  file:
    path: /root/cron.d/system
    owner: root
    group: root
    state: directory
    mode: '0700'
  tags: [cron]

- name: Deploy '/root/cron.d/system/flush.sh' File
  copy:
    src: flush.sh
    dest: /root/cron.d/system/flush.sh
    owner: root
    group: root
    mode: "0600"
  tags: [cron]

- name: Add '/root/cron.d/system/flush.sh' to Cron
  cron:
    name: "Flush Memory"
    minute: "*/1"
    user: root
    job: "/bin/bash /root/cron.d/system/flush.sh"
  tags: [cron]