---
- name: Common General
  import_tasks: common-general.yml

- name: Common Network
  import_tasks: common-network.yml

- name: Common DNS Resolver
  import_tasks: common-resolver.yml

- name: Common Time Sync
  import_tasks: common-time.yml

- name: Common Cron
  import_tasks: common-cron.yml

- name: Common Packages
  import_tasks: common-packages.yml

- name: Common SSH Service
  import_tasks: common-ssh.yml

- name: Common SCripts
  import_tasks: common-scripts.yml