---
- name: Configure '/etc/sysconfig/network-scripts/ifcfg-eth0' File
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  notify: "Restart Network Service"

- name: Configure '/etc/network/interfaces.d/eth0.conf' File
  template:
    src: eth0.conf.j2
    dest: /etc/network/interfaces.d/eth0.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  notify: "Restart Network Service"

- name: Install Chrony Service
  package:
    update_cache: yes
    name: chrony
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 8 or
    ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int == 8 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int == 7
  notify: "Start Time Service"

- name: Install NTP Service
  package:
    update_cache: yes
    name: ntp
    state: present
  when: (ansible_distribution != "OracleLinux" or ansible_distribution_major_version|int != 8) and
    (ansible_distribution != "OracleLinux" or ansible_distribution_major_version|int != 7) and
    (ansible_distribution != "CentOS" or ansible_distribution_major_version|int != 8) and
    (ansible_distribution != "CentOS" or ansible_distribution_major_version|int != 7)
  notify: "Start Time Service"

- name: Timezone to Europe/Warsaw
  timezone:
    name: Europe/Warsaw

- name: Disable UseDNS 'openssh-server'
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK - UserDNS #"
    state: present
    block: |
      UseDNS yes
  notify: "Restart SSH Service"

- name: Setup Hostname
  hostname:
    name: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version|int != 14

- set_fact:
    custom_ansbile_hostname: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}"

- name: Setup Hostname
  hostname:
    name: "{{ custom_ansbile_hostname }}"
    use: systemd
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14 and
    ansible_hostname != custom_ansbile_hostname

- name: Configure 'hosts' File
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Configure 'resolv.conf' File
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"

- name: Install 'python3'
  package:
    update_cache: yes
    name: python3
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int >= 8 or
    ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 9 or
    ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16

- name: Install 'python2'
  package:
    update_cache: yes
    name: python
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int < 8 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int < 8 or
    ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9 or
    ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 16

- name: Uninstall 'python3' in old Distributions
  package:
    name: python3
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int < 8 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int < 8 or
    ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9 or
    ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 16

- name: Uninstall 'python2' in new Distributions
  package:
    name: python2
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8 or
    ansible_distribution == "OracleLinux" and ansible_distribution_major_version|int >= 8 or
    ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 9 or
    ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16